controller_list:
  - name: fake_hand_controller
    joints:
      - right_base_hand_big_thumb_1
      - right_base_hand_big_thumb_2
      - right_base_hand_big_thumb_3
      - right_hand_finger_1_joint
      - right_hand_finger_shizhimid_joint
      - right_hand_finger_shizhitop_joint
      - right_hand_finger_2_joint
      - right_hand_finger_zhongzhimid_joint
      - right_hand_finger_zhongzhitop_joint
      - right_hand_finger_3_joint
      - right_hand_finger_wumingzhimid_joint
      - right_hand_finger_wumingzhitop_joint
      - right_hand_finger_4_joint
      - right_hand_finger_xiaozhimid_joint
      - right_hand_finger_xiaozhitop_joint
  - name: fake_xarm6_controller
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5
      - joint6
  - name: fake_arm_controller
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5
      - joint6
      - right_base_hand_big_thumb_1
      - right_base_hand_big_thumb_2
      - right_base_hand_big_thumb_3
      - right_hand_finger_1_joint
      - right_hand_finger_shizhimid_joint
      - right_hand_finger_shizhitop_joint
      - right_hand_finger_2_joint
      - right_hand_finger_zhongzhimid_joint
      - right_hand_finger_zhongzhitop_joint
      - right_hand_finger_3_joint
      - right_hand_finger_wumingzhimid_joint
      - right_hand_finger_wumingzhitop_joint
      - right_hand_finger_4_joint
      - right_hand_finger_xiaozhimid_joint
      - right_hand_finger_xiaozhitop_joint