xarm6:
# MoveIt-specific simulation settings
  moveit_sim_hw_interface:
    joint_model_group: controllers_initial_group_
    joint_model_group_pose: controllers_initial_pose_
# Settings for ros_control control loop
  generic_hw_control_loop:
    loop_hz: 300
    cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
  hardware_interface:
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5
      - joint6
      - right_base_hand_big_thumb_1
      - right_base_hand_big_thumb_2
      - right_base_hand_big_thumb_3
      - right_hand_finger_1_joint
      - right_hand_finger_shizhimid_joint
      - right_hand_finger_shizhitop_joint
      - right_hand_finger_2_joint
      - right_hand_finger_zhongzhimid_joint
      - right_hand_finger_zhongzhitop_joint
      - right_hand_finger_3_joint
      - right_hand_finger_wumingzhimid_joint
      - right_hand_finger_wumingzhitop_joint
      - right_hand_finger_4_joint
      - right_hand_finger_xiaozhimid_joint
      - right_hand_finger_xiaozhitop_joint
    sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50
  controller_list:
    - name: xarm6_controller
      action_ns: follow_joint_trajectory
      default: True
      type: FollowJointTrajectory
      joints:
        - joint1
        - joint2
        - joint3
        - joint4
        - joint5
        - joint6
    - name: hand_controller
      action_ns: follow_joint_trajectory
      default: True
      type: FollowJointTrajectory
      joints:
        - right_base_hand_big_thumb_1
        - right_base_hand_big_thumb_2
        - right_base_hand_big_thumb_3
        - right_hand_finger_1_joint
        - right_hand_finger_shizhimid_joint
        - right_hand_finger_shizhitop_joint
        - right_hand_finger_2_joint
        - right_hand_finger_zhongzhimid_joint
        - right_hand_finger_zhongzhitop_joint
        - right_hand_finger_3_joint
        - right_hand_finger_wumingzhimid_joint
        - right_hand_finger_wumingzhitop_joint
        - right_hand_finger_4_joint
        - right_hand_finger_xiaozhimid_joint
        - right_hand_finger_xiaozhitop_joint
    - name: arm_controller
      action_ns: follow_joint_trajectory
      default: True
      type: FollowJointTrajectory
      joints:
        - joint1
        - joint2
        - joint3
        - joint4
        - joint5
        - joint6
        - right_base_hand_big_thumb_1
        - right_base_hand_big_thumb_2
        - right_base_hand_big_thumb_3
        - right_hand_finger_1_joint
        - right_hand_finger_shizhimid_joint
        - right_hand_finger_shizhitop_joint
        - right_hand_finger_2_joint
        - right_hand_finger_zhongzhimid_joint
        - right_hand_finger_zhongzhitop_joint
        - right_hand_finger_3_joint
        - right_hand_finger_wumingzhimid_joint
        - right_hand_finger_wumingzhitop_joint
        - right_hand_finger_4_joint
        - right_hand_finger_xiaozhimid_joint
        - right_hand_finger_xiaozhitop_joint